name: Lint CSS/JS

on:
  push:
    # Only run if CSS/JS files changed.
    paths:
      - '**.js'
      - '**.css'
      - '.eslint*'
      - '.nvmrc'
      - '.prettier*'
      - '.stylelint*'
      - '**/package.json'
      - 'package-lock.json'
    branches:
      - master
      - develop
  pull_request:
    # Only run if CSS/JS files changed.
    paths:
      - '**.js'
      - '**.css'
      - '.eslint*'
      - '.nvmrc'
      - '.prettier*'
      - '.stylelint*'
      - '**/package.json'
      - 'package-lock.json'

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    timeout-minutes: 60
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Read .nvmrc
        run: echo "##[set-output name=NVMRC;]$(cat .nvmrc)"
        id: nvm

      - name: Setup Node
        uses: actions/setup-node@v2.1.5
        with:
          node-version: "14"

      - name: Cache node modules
        uses: pat-s/always-upload-cache@v2.1.5
        with:
          # npm cache files are stored in `~/.npm` on Linux/macOS
          path: ~/.npm
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-
        env:
          cache-name: cache-node-modules

      - name: Install dependencies
        run: npm ci
        env:
          CI: true
          PUPPETEER_SKIP_CHROMIUM_DOWNLOAD: true

      - name: CSS Lint
        run: npm run lint:css

      - name: JS Lint
        run: npm run lint:js
        continue-on-error: true
