name: JavaScript Unit Tests

on:
  push:
    # Only run if JS-related files changed.
    paths:
      - '**.js'
      - '**/package.json'
      - 'package-lock.json'
    branches:
      - main
      - release/*
  pull_request:
    # Only run if JS-related files changed.
    paths:
      - '**.js'
      - '**/package.json'
      - 'package-lock.json'

jobs:
  unit-js:
    name: Unit Tests
    runs-on: ubuntu-latest
    timeout-minutes: 60
    steps:

      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Node
        uses: actions/setup-node@v2.1.5
        with:
          node-version: '14'

      - name: Cache node modules
        uses: pat-s/always-upload-cache@v2.1.5
        with:
          # npm cache files are stored in `~/.npm` on Linux/macOS
          path: ~/.npm
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-
        env:
          cache-name: cache-node-modules

      - name: Setup Jest cache
        uses: actions/cache@v2.1.5
        id: cache-jest-cache
        with:
          path: .jest-cache
          key: ${{ runner.os }}-${{ steps.nvm.outputs.NVMRC }}-jest

      - name: Install dependencies
        run: |
          npm ci
        env:
          CI: true

      - name: Run JavaScript unit tests
        run: npm run test:js -- --runInBand --ci --cacheDirectory="$HOME/.jest-cache" --collectCoverage

